---
- name: Add nginx status configuration
  blockinfile:
    path: /etc/nginx/sites-available/{{ app_name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - METRICS"
    insertbefore: "location / {"
    block: |
      # Nginx status for metrics
      location /nginx_status {
          stub_status on;
          access_log off;
          allow 127.0.0.1;
          deny all;
      }
  notify: restart nginx
  ignore_errors: yes
