---
- name: Create redis_exporter user
  user:
    name: redis_exporter
    system: yes
    shell: /bin/false
    home: /var/lib/redis_exporter
    createhome: no

- name: Create redis_exporter directory
  file:
    path: /var/lib/redis_exporter
    state: directory
    owner: redis_exporter
    group: redis_exporter
    mode: '0755'

- name: Download redis_exporter
  get_url:
    url: "{{ redis_exporter_url }}"
    dest: /tmp/redis_exporter.tar.gz
    mode: '0644'

- name: Extract redis_exporter
  unarchive:
    src: /tmp/redis_exporter.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Install redis_exporter binary
  copy:
    src: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64/redis_exporter"
    dest: /usr/local/bin/redis_exporter
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Create redis_exporter service file
  template:
    src: redis_exporter.service.j2
    dest: /etc/systemd/system/redis_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart redis_exporter

- name: Enable and start redis_exporter
  systemd:
    name: redis_exporter
    enabled: yes
    state: started
    daemon_reload: yes