---
zentravision:
  hosts:
    zentravision-uat:
      ansible_host: 34.58.128.35
      ansible_user: zentravision
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  vars:
    gcp_project_id: zentraflow
    environment: uat
    domain_name: "uat-zentravision.zentratek.com"
    admin_email: "admin@zentratek.com"
    app_repo_url: "https://github.com/jfbm74/zentravision.git"
    app_version: main
    
    # Django superuser
    django_create_superuser: true
    django_superuser_username: admin
    django_superuser_email: "admin@zentratek.com"
    django_superuser_password: "UatPassword123!"
    
    # UAT settings
    debug_mode: false
    ssl_enabled: true
    backup_enabled: true
