---
zentravision:
  hosts:
    zentravision-uat:
      ansible_host: [33m╷[0m[0m
[33m│[0m [0m[1m[33mWarning: [0m[0m[1mNo outputs found[0m
[33m│[0m [0m
[33m│[0m [0m[0mThe state file either has no outputs defined, or all the defined outputs
[33m│[0m [0mare empty. Please define an output in your configuration with the `output`
[33m│[0m [0mkeyword and run `terraform refresh` for it to become available. If you are
[33m│[0m [0musing interpolation, please verify the interpolated value is not empty. You
[33m│[0m [0mcan use the `terraform console` command to assist.
[33m╵[0m[0m
      ansible_user: zentravision
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  vars:
    gcp_project_id: zentravision
    environment: uat
    domain_name: "uat-zentravision.zentratek.com"
    admin_email: "consultoria@zentratek.com"
    app_repo_url: "https://github.com/jfbm74/zentravision.git"
    app_version: main
    
    # Django superuser
    django_create_superuser: true
    django_superuser_username: admin
    django_superuser_email: "consultoria@zentratek.com"
    django_superuser_password: "UatPassword123!"
    
    # UAT settings
    debug_mode: false
    ssl_enabled: true
    backup_enabled: true
    # Celery configuration for UAT
    celery_worker_concurrency: 3
    celery_log_level: "info"
