---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - unzip
      - git
      - htop
      - vim
      - ufw
      - fail2ban
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Configure UFW firewall
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "22"
    - "80"
    - "443"
    - "8000"
  when: firewall_enabled | default(true)

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
  when: firewall_enabled | default(true)

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  when: fail2ban_enabled | default(true)
  notify: restart fail2ban

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
  when: fail2ban_enabled | default(true)
