---
zentravision:
  hosts:
    zentravision-dev:
      ansible_host: 34.45.112.122
      ansible_user: zentravision
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  vars:
    gcp_project_id: zentraflow
    environment: dev
    domain_name: "dev-zentravision.zentratek.com"
    admin_email: "consultoria@zentratek.com"
    app_repo_url: "https://github.com/jfbm74/zentravision.git"
    app_version: develop
    
    # Django superuser
    django_create_superuser: true
    django_superuser_username: admin
    django_superuser_email: "consultoria@zentratek.com"
    django_superuser_password: "DevPassword123!"
    
    # Dev settings - HABILITAR SSL
    debug_mode: true
    ssl_enabled: true
    backup_enabled: false
