---
# Global variables for production environment
gcp_project_id: zentraflow
environment: prod

# Application settings
app_name: zentravision
app_repo_url: "https://github.com/jfbm74/zentravision.git"
app_version: main

# Domain configuration
domain_name: "{{ vault_domain_name | default('zentravision.ejemplo.com') }}"
admin_email: "{{ vault_admin_email | default('admin@ejemplo.com') }}"

# Django settings
django_create_superuser: true
django_superuser_username: admin
django_superuser_email: "{{ admin_email }}"
django_superuser_password: "{{ vault_django_superuser_password | default('ChangeMe123!') }}"

# SSL and security
ssl_enabled: true
firewall_enabled: true

# Backup settings
backup_enabled: true
backup_retention_days: 30
