---
# Global variables for UAT environment
gcp_project_id: zentraflow
environment: uat

# Application settings
app_name: zentravision
app_repo_url: "https://github.com/jfbm74/zentravision.git"
app_version: main

# Domain configuration
domain_name: "uat-zentravision.zentratek.com"
admin_email: "admin@zentratek.com"

# Django settings
django_create_superuser: true
django_superuser_username: admin
django_superuser_email: "admin@zentratek.com"
django_superuser_password: "UatPassword123!"

# SSL and security
ssl_enabled: true
firewall_enabled: true

# Backup settings
backup_enabled: true
backup_retention_days: 15

# UAT-specific settings
debug_mode: false
log_level: INFO

# ============================================
# NEW: Performance and Timeout Configuration
# ============================================

# Gunicorn settings for AI processing
gunicorn_workers: 2
gunicorn_timeout: 300  # 5 minutes for AI processing
gunicorn_keep_alive: 2
gunicorn_max_requests: 500
gunicorn_max_requests_jitter: 50
gunicorn_worker_class: sync
gunicorn_worker_connections: 1000

# Nginx settings for large file uploads
nginx_max_body_size: "50M"  # PDF uploads
nginx_body_buffer_size: "128k"
nginx_proxy_timeout: "300s"  # 5 minutes
nginx_send_timeout: "300s"
nginx_proxy_buffer_size: "64k"
nginx_proxy_buffers: "8 64k"
nginx_proxy_busy_buffers: "128k"

# Celery settings (if used)
celery_worker_concurrency: 1
celery_max_memory: 100000
celery_time_limit: 180
celery_soft_time_limit: 150